version: '3'

services:
  travel-app:
    build: .
    environment:
      FLASK_APP: run.py
      SQLALCHEMY_DATABASE_URI: "$SQLALCHEMY_DATABASE_URI"
    ports:
      - "5000:5000"
    volumes: [".:/app"]
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    networks:
      - travel-network
  travel_db:
    image: postgres:12.5-alpine
    restart: always
    environment:
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

